### ISSUE TITLE
ATTENTION! - REPOSITORY HAS MOVED - DO NOT OPEN ISSUES HERE - LINK IN DESCRIPTION

### ISSUE THREAD

**Issue by MonzUn** [Eco-DiscordLink/EcoDiscordPlugin#18]
New issues page at https://github.com/Eco-DiscordLink/EcoDiscordPlugin/issues.

**Comment by Dave247** [comment]
@MonzUn I get that you copied all existing tickets from the old repository to the new one, though you might want to edit the title of this issue here in the new repo just in case so it's not confusing. 😛 

You should also be able to achieve the old one to become read-only so there won't be any risk of someone interacting and opening a ticket on it
