### ISSUE TITLE
Names of items are cut off, making the bot pretty useless

### ISSUE THREAD

**Issue by Azzurite** [Eco-DiscordLink/EcoDiscordPlugin#61]
![image](https://user-images.githubusercontent.com/2777158/133291320-de1c9350-1784-4314-9a9f-fc453ffa84e6.png)

The marked area in the image contains "Mortared Stone Chairs", "Mortared Stone Benches", "Mortared Stone Tables" and so on. Not being able to distinguish between those makes the whole thing pretty pointless.

**Comment by MonzUn** [comment]
This is due to a change made by Discord, not me so I don't appreciate nor deserve the rudeness.
This is pretty far down my list of things to change, so if you want that you'll have to do it yourself.

The next time you want to ask for changes, try approaching them without calling the entire work useless and you might have a better chance getting what you want.

**Comment by Azzurite** [comment]
I did not intent any rudeness, just stating a fact. Not being able to figure out what is being sold does make the command useless, as that is its main purpose. I'm sorry if I have offended you.
