### ISSUE TITLE
Serialization Exception blocking plugin to function

### ISSUE THREAD

**Issue by X-Niter** [Eco-DiscordLink/EcoDiscordPlugin#68]
Your 2.2.3 download, was running it for a solid 3 days then it died completely. 

I made a whole new server/instance, and now all the sudden it does not work at all. 
Same config, I don't see any typo's, nor was anything changed to block it.

Here is the logging I get about the error.

I'm on #5 of deleting the whole server and rebuilding it thinking I had to mess up somewhere, I keep thinking the config is goofed because of a Serialization stack trace, but nothing comes up as a resolvent..

https://pastebin.com/9zegfXd1

**Comment by DarkMukke** [comment]
this is because the D#+ bundled in this mod is outdated and the discord api since has changed,

PR #70 fixes this but you'll have to compile the DDLs yourself, I could create a zipfile of the modfile DDLs if you want and put it up as a release on my fork, let me know if you'll be able to compile them yourself

**Comment by X-Niter** [comment]
Hey there! Yes, I'm tracking all of that, I recall being in the discord and being apart of the comversation regarding all of that. This can be closed without any further more discussion! Thank you

**Comment by MonzUn** [comment]
This will get resolved tomorrow when Eco 9.5 releases officially and DL 2.2.3 is replaced by 3.0.0.

**Comment by X-Niter** [comment]
Thanks for the update there! Good job!
